"TRUTH":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]

"CORRECTION":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "TrueMain":
                        - "equal": True

"CALIBRATION":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "TrueMain":
                        - "equal": True

"DISCRIMINATION":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":    
                        - "equal": 0
                - "TrueMain":
                        - "equal": True

"RECONSTRUCTION":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "TrueMain":
                        - "equal": True

"SMEARING":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "TrueMain":
                        - "equal": True

"ANALYSIS":
        - "Config": null
        - "Truth":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "SignalParticleX":
                        - "absbetween": [0, 330]
                - "SignalParticleY":
                        - "absbetween": [0, 675]
                - "SignalParticleZ":
                        - "between": [0, 2100]
                - "TrueMain":
                        - "equal": True